# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: herzog

# SEO
marketing:
  seo:
    site_type: Organization
    local_business_type: 'Herzog Lab'
    org_name: 'Herzog Lab'
    description: 'Leading research lab advancing knowledge through innovative scientific discovery and collaboration.'
    twitter: ''
  analytics:
    google_analytics: 'G-5FZTCK726Q'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      filename: "logo.png"
      filename_hover: "logo-hover.png"
      text: 'Research Lab'

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Herzog Lab, made with <a href="https://hugoblox.com/">HugoBlox</a>.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

# Pro features
pro:
  hide_attribution: true
